version: '3.8'

volumes:
  localstack-vol:

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: data_warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"

  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - localstack-vol:/var/lib/localstack

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:5432 -t 90s -i 250ms
    #networks:
    #  - internal

  createbuckets:
    image: amazon/aws-cli
    depends_on:
      - localstack
    environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_REGION}
        - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    entrypoint: >
      /bin/sh -c "
      aws --endpoint-url=http://localstack:4566 s3 mb s3://${AWS_BUCKET_NAME};
      "
