version: "3.8"

services:
  localstack:
    image: localstack/localstack
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      # - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      # - "/var/run/docker.sock:/var/run/docker.sock"
