
[tool.pylint.messages_control]

disable=[
    "missing-function-docstring",
    "missing-module-docstring"
]


[tool.isort]
multi_line_output = 3
length_sort = true

[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true
